#define IRIS_MAP_WIDTH  503
#define IRIS_MAP_HEIGHT 80

#define SCLERA_WIDTH 375
#define SCLERA_HEIGHT 375

#define SCREEN_WIDTH 240
#define SCREEN_HEIGHT 240

#define IRIS_WIDTH  160
#define IRIS_HEIGHT 160

#define SYMMETRICAL_EYELID
